version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true